# Generated by Django 5.0.1 on 2024-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeHistogramMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'agehistogram_materialized_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgeRangeMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=255)),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'agerange_materialized_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoxesGenderMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client_gender', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'boxes_gender_materialized_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieGenderMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('amount_sum', models.FloatField()),
            ],
            options={
                'db_table': 'pie_gender_materialized_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_sum', models.FloatField()),
            ],
            options={
                'db_table': 'time_series_materialized_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopClientsMaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'topclients_materialized_view',
                'managed': False,
            },
        ),
    ]
